// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCENYIMl_Pb9PsSa5-5pv9yNQhcOH2142o',
    appId: '1:1089973926451:web:c5238abee4a4cb0e2ac146',
    messagingSenderId: '1089973926451',
    projectId: 'reinternproject',
    authDomain: 'reinternproject.firebaseapp.com',
    storageBucket: 'reinternproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlSdbMTeHiHcGLRLeSUoR8GamBHrlQvCY',
    appId: '1:1089973926451:android:52272a119433c3a12ac146',
    messagingSenderId: '1089973926451',
    projectId: 'reinternproject',
    storageBucket: 'reinternproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfUV9YYIfp0yHCkB6vzC3w9d04zgx_m6M',
    appId: '1:1089973926451:ios:dad47a34550fb1702ac146',
    messagingSenderId: '1089973926451',
    projectId: 'reinternproject',
    storageBucket: 'reinternproject.firebasestorage.app',
    iosBundleId: 'com.example.hhproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfUV9YYIfp0yHCkB6vzC3w9d04zgx_m6M',
    appId: '1:1089973926451:ios:dad47a34550fb1702ac146',
    messagingSenderId: '1089973926451',
    projectId: 'reinternproject',
    storageBucket: 'reinternproject.firebasestorage.app',
    iosBundleId: 'com.example.hhproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCENYIMl_Pb9PsSa5-5pv9yNQhcOH2142o',
    appId: '1:1089973926451:web:47f9b01e0cff4edb2ac146',
    messagingSenderId: '1089973926451',
    projectId: 'reinternproject',
    authDomain: 'reinternproject.firebaseapp.com',
    storageBucket: 'reinternproject.firebasestorage.app',
  );
}
